export type Product = {
  name: string;
  slug: string;
  price: number;
  image: string;
  hint: string;
  category: 'Tops' | 'Bottoms' | 'Dresses' | 'Accessories';
  description: string;
  featured: boolean;
};

export const products: Product[] = [
    // Dresses
    {
      name: "Floral Maxi Dress",
      slug: "floral-maxi-dress",
      price: 3299,
      image: "https://images.unsplash.com/photo-1594744806549-844414798e85?auto=format&fit=crop&w=400&q=80",
      hint: "floral maxi dress",
      category: 'Dresses',
      description: "A stunning floral maxi dress perfect for summer days. Made from lightweight and breathable fabric.",
      featured: true,
    },
    {
      name: "Satin Slip Dress",
      slug: "satin-slip-dress",
      price: 2899,
      image: "https://images.unsplash.com/photo-1627914650529-51fc612b487c?auto=format&fit=crop&w=400&q=80",
      hint: "satin slip dress",
      category: 'Dresses',
      description: "Elegant and chic, this satin slip dress is a versatile addition to your wardrobe. Perfect for evening events.",
      featured: false,
    },
    {
      name: "Ruffled Mini Dress",
      slug: "ruffled-mini-dress",
      price: 2499,
      image: "https://images.unsplash.com/photo-1574488334461-15fad64ab3b4?auto=format&fit=crop&w=400&q=80",
      hint: "ruffled mini dress",
      category: 'Dresses',
      description: "Fun and flirty, this ruffled mini dress features a playful design with delicate details.",
      featured: false,
    },
    {
      name: "Linen Shirt Dress",
      slug: "linen-shirt-dress",
      price: 3199,
      image: "https://images.unsplash.com/photo-1621575884398-654a939a3f29?auto=format&fit=crop&w=400&q=80",
      hint: "linen shirt dress",
      category: 'Dresses',
      description: "Stay cool and comfortable in this classic linen shirt dress. A timeless piece for any occasion.",
      featured: true,
    },
    {
      name: "Knit Bodycon Dress",
      slug: "knit-bodycon-dress",
      price: 2799,
      image: "https://images.unsplash.com/photo-1614488323863-1268594241fc?auto=format&fit=crop&w=400&q=80",
      hint: "knit bodycon dress",
      category: 'Dresses',
      description: "Highlight your curves with this stylish knit bodycon dress. Made from a comfortable stretch fabric.",
      featured: false,
    },
    {
      name: "Polka Dot Midi Dress",
      slug: "polka-dot-midi-dress",
      price: 3099,
      image: "https://images.unsplash.com/photo-1590451999233-a36f3e786312?auto=format&fit=crop&w=400&q=80",
      hint: "polka dot dress",
      category: 'Dresses',
      description: "A playful polka dot midi dress that adds a touch of retro charm to your look.",
      featured: false,
    },
    {
      name: "Off-Shoulder Dress",
      slug: "off-shoulder-dress",
      price: 2599,
      image: "https://images.unsplash.com/photo-1551843194-85513233c1a8?auto=format&fit=crop&w=400&q=80",
      hint: "woman off shoulder",
      category: 'Dresses',
      description: "Show off your shoulders with this elegant and romantic off-shoulder dress.",
      featured: true,
    },
    {
      name: "A-Line Skater Dress",
      slug: "a-line-skater-dress",
      price: 2399,
      image: "https://images.unsplash.com/photo-1595133283412-343513b4d241?auto=format&fit=crop&w=400&q=80",
      hint: "skater dress",
      category: 'Dresses',
      description: "A classic A-line skater dress that is both flattering and comfortable for everyday wear.",
      featured: false,
    },
    {
      name: "Bohemian Wrap Dress",
      slug: "bohemian-wrap-dress",
      price: 3499,
      image: "https://images.unsplash.com/photo-1590452366881-a75678b6f3b0?auto=format&fit=crop&w=400&q=80",
      hint: "bohemian dress",
      category: 'Dresses',
      description: "Embrace a free-spirited style with this beautiful bohemian wrap dress, featuring intricate patterns.",
      featured: false,
    },
    {
      name: "Classic Little Black Dress",
      slug: "classic-little-black-dress",
      price: 2999,
      image: "https://images.unsplash.com/photo-1583117181238-b9969f9843a9?auto=format&fit=crop&w=400&q=80",
      hint: "black dress",
      category: 'Dresses',
      description: "Every wardrobe needs a little black dress. This classic piece is perfect for any event.",
      featured: false,
    },
    { name: 'Sequin Party Dress', slug: 'sequin-party-dress', price: 4999, image: 'https://images.unsplash.com/photo-1574556163315-7a6372c36a32?auto=format&fit=crop&w=400&q=80', hint: 'sequin party dress', category: 'Dresses', description: "Shine bright at your next party with this dazzling sequin dress.", featured: false },
    { name: 'Velvet Evening Gown', slug: 'velvet-evening-gown', price: 5499, image: 'https://images.unsplash.com/photo-1599818858882-72166a0d241d?auto=format&fit=crop&w=400&q=80', hint: 'velvet evening gown', category: 'Dresses', description: "A luxurious velvet evening gown for a glamorous and sophisticated look.", featured: false },
    { name: 'Puff Sleeve Dress', slug: 'puff-sleeve-dress', price: 3399, image: 'https://images.unsplash.com/photo-1609382354932-510c49b6b757?auto=format&fit=crop&w=400&q=80', hint: 'puff sleeve dress', category: 'Dresses', description: "Make a statement with this trendy puff sleeve dress, perfect for a chic day out.", featured: false },


    // Bottoms
    {
      name: "High-Waisted Jeans",
      slug: "high-waisted-jeans",
      price: 2599,
      image: "https://images.unsplash.com/photo-1604176354204-926873782855?auto=format&fit=crop&w=400&q=80",
      hint: "high waisted jeans",
      category: 'Bottoms',
      description: "A flattering pair of high-waisted jeans that will become a staple in your wardrobe.",
      featured: true,
    },
    {
      name: "Pleated Trousers",
      slug: "pleated-trousers",
      price: 2299,
      image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=400&q=80",
      hint: "pleated trousers",
      category: 'Bottoms',
      description: "Sophisticated and comfortable, these pleated trousers are perfect for the office or a casual day out.",
      featured: false,
    },
    {
      name: "Wide-Leg Linen Pants",
      slug: "wide-leg-linen-pants",
      price: 2899,
      image: "https://images.unsplash.com/photo-1603217183024-d2c613039c94?auto=format&fit=crop&w=400&q=80",
      hint: "linen pants",
      category: 'Bottoms',
      description: "Breezy and stylish wide-leg linen pants for a relaxed and chic summer look.",
      featured: false,
    },
    {
      name: "Denim Skirt",
      slug: "denim-skirt",
      price: 1899,
      image: "https://images.unsplash.com/photo-1584273147793-9a3e63b4f620?auto=format&fit=crop&w=400&q=80",
      hint: "denim skirt",
      category: 'Bottoms',
      description: "A versatile denim skirt that can be dressed up or down for any occasion.",
      featured: true,
    },
    {
      name: "Cargo Pants",
      slug: "cargo-pants",
      price: 2799,
      image: "https://images.unsplash.com/photo-1608405051996-480da50f3c4c?auto=format&fit=crop&w=400&q=80",
      hint: "cargo pants",
      category: 'Bottoms',
      description: "Trendy and functional cargo pants with multiple pockets for a cool, utilitarian vibe.",
      featured: false,
    },
    {
      name: "Satin Midi Skirt",
      slug: "satin-midi-skirt",
      price: 2499,
      image: "https://images.unsplash.com/photo-1589531737424-a212215c5831?auto=format&fit=crop&w=400&q=80",
      hint: "satin midi skirt",
      category: 'Bottoms',
      description: "A luxurious satin midi skirt that drapes beautifully for an elegant silhouette.",
      featured: false,
    },
    {
      name: "Tailored Shorts",
      slug: "tailored-shorts",
      price: 1999,
      image: "https://images.unsplash.com/photo-1591130902253-91c2c06135b5?auto=format&fit=crop&w=400&q=80",
      hint: "tailored shorts",
      category: 'Bottoms',
      description: "Chic and polished, these tailored shorts are a summer wardrobe essential.",
      featured: false,
    },
    {
      name: "Leather Leggings",
      slug: "leather-leggings",
      price: 3199,
      image: "https://images.unsplash.com/photo-1512316041697-d3f08f840c5f?auto=format&fit=crop&w=400&q=80",
      hint: "leather leggings",
      category: 'Bottoms',
      description: "Add some edge to your look with these sleek and comfortable faux leather leggings.",
      featured: false,
    },
    {
      name: "Jogger Sweatpants",
      slug: "jogger-sweatpants",
      price: 2199,
      image: "https://images.unsplash.com/photo-1563241527-547565ca4086?auto=format&fit=crop&w=400&q=80",
      hint: "jogger sweatpants",
      category: 'Bottoms',
      description: "Stay comfortable and stylish with these soft and cozy jogger sweatpants.",
      featured: false,
    },
    {
      name: "Plaid Mini Skirt",
      slug: "plaid-mini-skirt",
      price: 1999,
      image: "https://images.unsplash.com/photo-1580214690239-0097a5518428?auto=format&fit=crop&w=400&q=80",
      hint: "plaid mini skirt",
      category: 'Bottoms',
      description: "A classic plaid mini skirt for a preppy and stylish look.",
      featured: false,
    },
    { name: 'Corduroy Pants', slug: 'corduroy-pants', price: 2699, image: 'https://images.unsplash.com/photo-1611808682855-081b37380996?auto=format&fit=crop&w=400&q=80', hint: 'corduroy pants', category: 'Bottoms', description: 'Retro-inspired corduroy pants that are both stylish and comfortable.', featured: false },
    { name: 'Bike Shorts', slug: 'bike-shorts', price: 1599, image: 'https://images.unsplash.com/photo-1591904128994-6f3938488a7b?auto=format&fit=crop&w=400&q=80', hint: 'bike shorts', category: 'Bottoms', description: 'Versatile and comfortable bike shorts for workouts or casual wear.', featured: false },
    
    // Accessories
    {
      name: "Leather Tote Bag",
      slug: "leather-tote-bag",
      price: 4599,
      image: "https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=400&q=80",
      hint: "leather tote bag",
      category: 'Accessories',
      description: "A spacious and stylish leather tote bag that can carry all your essentials.",
      featured: true,
    },
    {
      name: "Gold Hoop Earrings",
      slug: "gold-hoop-earrings",
      price: 1299,
      image: "https://images.unsplash.com/photo-1615951663185-3932a3c75a93?auto=format&fit=crop&w=400&q=80",
      hint: "gold hoop earrings",
      category: 'Accessories',
      description: "Classic gold hoop earrings that add a touch of elegance to any outfit.",
      featured: false,
    },
    {
      name: "Classic Wristwatch",
      slug: "classic-wristwatch",
      price: 5899,
      image: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=400&q=80",
      hint: "classic wristwatch",
      category: 'Accessories',
      description: "A timeless and elegant wristwatch that combines style and function.",
      featured: true,
    },
    {
      name: "Silk Scarf",
      slug: "silk-scarf",
      price: 1499,
      image: "https://images.unsplash.com/photo-1562149481-02e49c716c6d?auto=format&fit=crop&w=400&q=80",
      hint: "silk scarf",
      category: 'Accessories',
      description: "A luxurious silk scarf with a beautiful print to elevate your look.",
      featured: false,
    },
    {
      name: "Cat-Eye Sunglasses",
      slug: "cat-eye-sunglasses",
      price: 2199,
      image: "https://images.unsplash.com/photo-1577803645773-f4208249dd7c?auto=format&fit=crop&w=400&q=80",
      hint: "cat eye sunglasses",
      category: 'Accessories',
      description: "Chic and stylish cat-eye sunglasses to protect your eyes and make a statement.",
      featured: false,
    },
    {
      name: "Layered Necklace",
      slug: "layered-necklace",
      price: 1799,
      image: "https://images.unsplash.com/photo-1611652022417-a55109d9342c?auto=format&fit=crop&w=400&q=80",
      hint: "layered necklace",
      category: 'Accessories',
      description: "A delicate and trendy layered necklace to complete your look.",
      featured: false,
    },
    {
      name: "Leather Belt",
      slug: "leather-belt",
      price: 1599,
      image: "https://images.unsplash.com/photo-1557252273-01c36642142a?auto=format&fit=crop&w=400&q=80",
      hint: "leather belt",
      category: 'Accessories',
      description: "A high-quality leather belt to cinch your waist and complete your outfit.",
      featured: false,
    },
    {
      name: "Straw Hat",
      slug: "straw-hat",
      price: 1899,
      image: "https://images.unsplash.com/photo-1533282173-265141a43a0d?auto=format&fit=crop&w=400&q=80",
      hint: "straw hat",
      category: 'Accessories',
      description: "A wide-brim straw hat perfect for sunny days and beach getaways.",
      featured: false,
    },
    {
      name: "Crossbody Bag",
      slug: "crossbody-bag",
      price: 3499,
      image: "https://images.unsplash.com/photo-1579631621533-35f953ef2113?auto=format&fit=crop&w=400&q=80",
      hint: "crossbody bag",
      category: 'Accessories',
      description: "A practical and stylish crossbody bag for hands-free convenience.",
      featured: false,
    },
    {
      name: "Statement Ring Set",
      slug: "statement-ring-set",
      price: 1199,
      image: "https://images.unsplash.com/photo-1603372234476-353a3a4049a4?auto=format&fit=crop&w=400&q=80",
      hint: "statement ring set",
      category: 'Accessories',
      description: "A set of beautiful statement rings to adorn your fingers.",
      featured: false,
    },
    { name: 'Beanie Hat', slug: 'beanie-hat', price: 1299, image: 'https://images.unsplash.com/photo-1575428652377-a3d80e281475?auto=format&fit=crop&w=400&q=80', hint: 'beanie hat', category: 'Accessories', description: 'A cozy and stylish beanie hat to keep you warm in colder months.', featured: false },
    { name: 'Canvas Backpack', slug: 'canvas-backpack', price: 3899, image: 'https://images.unsplash.com/photo-1553062407-98eeb6e0e5c8?auto=format&fit=crop&w=400&q=80', hint: 'canvas backpack', category: 'Accessories', description: 'A durable and spacious canvas backpack for all your adventures.', featured: false },

     // Tops
    { name: 'Classic White Tee', slug: 'classic-white-tee', price: 1299, image: 'https://images.unsplash.com/photo-1581655353422-34693a595a6a?auto=format&fit=crop&w=400&q=80', hint: 'white t-shirt', category: 'Tops', description: 'A must-have classic white tee made from soft, high-quality cotton.', featured: false },
    { name: 'Silk Cami Top', slug: 'silk-cami-top', price: 1899, image: 'https://images.unsplash.com/photo-1542295393-16a1c185121c?auto=format&fit=crop&w=400&q=80', hint: 'silk cami top', category: 'Tops', description: 'A luxurious silk cami top that can be dressed up or down.', featured: false },
    { name: 'Oversized Hoodie', slug: 'oversized-hoodie', price: 2999, image: 'https://images.unsplash.com/photo-1556821854-5775c7484a44?auto=format&fit=crop&w=400&q=80', hint: 'oversized hoodie', category: 'Tops', description: 'The perfect oversized hoodie for ultimate comfort and style.', featured: false },
    { name: 'Striped Long Sleeve', slug: 'striped-long-sleeve', price: 1999, image: 'https://images.unsplash.com/photo-1550928434-a2125816913c?auto=format&fit=crop&w=400&q=80', hint: 'striped long sleeve', category: 'Tops', description: 'A timeless striped long-sleeve top for a classic, nautical look.', featured: false },
    { name: 'Cropped Sweater', slug: 'cropped-sweater', price: 2499, image: 'https://images.unsplash.com/photo-1588143216885-3162a03525e9?auto=format&fit=crop&w=400&q=80', hint: 'cropped sweater', category: 'Tops', description: 'A trendy cropped sweater that pairs perfectly with high-waisted bottoms.', featured: false },
    { name: 'Lace Blouse', slug: 'lace-blouse', price: 2199, image: 'https://images.unsplash.com/photo-1622359516643-983f4b5f8841?auto=format&fit=crop&w=400&q=80', hint: 'lace blouse', category: 'Tops', description: 'An elegant lace blouse with intricate details for a romantic look.', featured: false },
    { name: 'Graphic T-Shirt', slug: 'graphic-t-shirt', price: 1499, image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=400&q=80', hint: 'graphic t-shirt', category: 'Tops', description: 'Express yourself with this cool and comfortable graphic t-shirt.', featured: false },
    { name: 'Denim Jacket', slug: 'denim-jacket', price: 3599, image: 'https://images.unsplash.com/photo-1543087902-386568695020?auto=format&fit=crop&w=400&q=80', hint: 'denim jacket', category: 'Tops', description: 'A timeless denim jacket that is a perfect layering piece for any season.', featured: false },
    { name: 'Button-Down Shirt', slug: 'button-down-shirt', price: 2299, image: 'https://images.unsplash.com/photo-1589938833917-7429135071d3?auto=format&fit=crop&w=400&q=80', hint: 'button-down shirt', category: 'Tops', description: 'A crisp and classic button-down shirt for a polished look.', featured: false },
    { name: 'Turtleneck Top', slug: 'turtleneck-top', price: 1799, image: 'https://images.unsplash.com/photo-1581044777550-4cfa6ce998c3?auto=format&fit=crop&w=400&q=80', hint: 'turtleneck top', category: 'Tops', description: 'A sleek and sophisticated turtleneck top, perfect for layering.', featured: false },
    { name: 'Ribbed Tank Top', slug: 'ribbed-tank-top', price: 999, image: 'https://images.unsplash.com/photo-1530286623682-9435a3962d3a?auto=format&fit=crop&w=400&q=80', hint: 'ribbed tank top', category: 'Tops', description: 'A basic ribbed tank top that is a versatile wardrobe essential.', featured: false },
    { name: 'Peplum Blouse', slug: 'peplum-blouse', price: 2399, image: 'https://images.unsplash.com/photo-1594938294985-a7455a0697a2?auto=format&fit=crop&w=400&q=80', hint: 'peplum blouse', category: 'Tops', description: 'A flattering peplum blouse that accentuates the waist.', featured: false },
    { name: 'Flannel Shirt', slug: 'flannel-shirt', price: 2899, image: 'https://images.unsplash.com/photo-1509402361652-afd137976b71?auto=format&fit=crop&w=400&q=80', hint: 'flannel shirt', category: 'Tops', description: 'A cozy flannel shirt perfect for a casual, layered look.', featured: true },
  ];
